version: '3.7'
services:
    zebracli:
        build: docker
        image: murfffi/zebracli 
    native:
        # Used for native builds
        build: 
            context: ./graalvm
            args: 
                GID: ${GID:-0}
                UID: ${UID:-0}
        volumes: 
           - ".:/home/mvnuser/src"
           - "${HOME}/.m2:/home/mvnuser/.m2"
        working_dir: /home/mvnuser/src
        environment: 
            MVNW_VERBOSE: "true"
