/*-
 * #%L
 * zebra4j
 * %%
 * Copyright (C) 2020 Marin Nozhchev
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * #L%
 */
package zebra4j;

import java.util.NoSuchElementException;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.chocosolver.solver.Settings;

/**
 * Solver for {@link QuestionPuzzle}
 */
public class QuestionPuzzleSolver {

	private final QuestionPuzzle qPuzzle;
	private final PuzzleSolver solver;

	public QuestionPuzzleSolver(QuestionPuzzle qPuzzle) {
		this.qPuzzle = qPuzzle;
		this.solver = new PuzzleSolver(qPuzzle.getPuzzle());
	}

	/**
	 * Configure the settings for the underlying SAT solver
	 * 
	 * @param chocoSettings required
	 */
	public void setChocoSettings(Settings chocoSettings) {
		solver.setChocoSettings(chocoSettings);
	}

	/**
	 * @return the set of solutions - answers to the question that satisfy a puzzle.
	 *         The list will be empty if the puzzle contains contradicting rules or
	 *         facts. Puzzles generated by {@link QuestionPuzzleGenerator} have a
	 *         single solution and the collection will have a single element.
	 */
	public Set<Attribute> solve() {
		return solveToStream().collect(Collectors.toSet());
	}

	/**
	 * @return the stream of all solutions
	 * 
	 * @see #solve()
	 */
	public Stream<Attribute> solveToStream() {
		return solver.solveChoco().flatMap(solution -> qPuzzle.getQuestion().answer(solution));
	}

	/**
	 * @return a single solution to the puzzle, useful for puzzles that were
	 *         generated by {@link QuestionPuzzleGenerator} and are guaranteed to
	 *         have a single solution
	 * @throws NoSuchElementException if the puzzle doesn't have any solutions
	 */
	public Attribute solveSingle() {
		return solveToStream().findAny().get();
	}
}
